[package]
name = "remote-poe-host"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
host-core = { path = "../host-core" }
serde = { version = "1", features = ["derive"] }
signaling-server = { path = "../signaling-server" }
tauri = { version = "2", features = ["tray-icon"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
